// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kveiaruikeyrkglanzta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2ZWlhcnVpa2V5cmtnbGFuenRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjYxMTksImV4cCI6MjA2NDE0MjExOX0.3S6O_dsx4Xj1rl4RpNg6F59IV0SD4cG03c2nnvlH_G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});